name: release-desktop-client
on: 
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - run: yarn electron-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_VERSION_NUMBER: '1.0.$GITHUB_RUN_ID'